<a href="https://colab.research.google.com/github/rickiepark/the-ml-book/blob/main/Ch03~02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 로지스틱 회귀

In [1]:
from sklearn.datasets import load_iris

In [2]:
X, y = load_iris(return_X_y=True, as_frame=True)

In [3]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [4]:
y.value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [5]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X, y)

LogisticRegression(max_iter=1000)

In [6]:
model.coef_, model.intercept_

(array([[-0.42415938,  0.96633485, -2.5160372 , -1.08205245],
        [ 0.53464109, -0.32039706, -0.20702001, -0.94324899],
        [-0.11048172, -0.64593779,  2.72305721,  2.02530144]]),
 array([  9.85533212,   2.23415948, -12.0894916 ]))

In [7]:
model.score(X, y)

0.9733333333333334

In [8]:
model.predict(X[0:1])

array([0])

In [9]:
model.decision_function(X[0:1])

array([[  7.33542869,   3.36096153, -10.69639022]])

In [10]:
x0 = X[0:1].to_numpy()
x0

array([[5.1, 3.5, 1.4, 0.2]])

In [11]:
import numpy as np

np.dot(x0, model.coef_.T) + model.intercept_

array([[  7.33542869,   3.36096153, -10.69639022]])

In [12]:
model.predict_proba(X[0:1])

array([[9.81557202e-01, 1.84427831e-02, 1.44809203e-08]])